theme: jekyll-theme-cayman
title: Click and drag elicitation tool
description: Click and drag elicitation tool
github:
  zip_url: https://github.com/beliefelicitation/graph
  another_url: https://beliefelicitation.herokuapp.com/demo
